#!/usr/bin/env node

/**
 * inject-env.js - Injects environment variables into a deployed config file
 * 
 * This runs during Netlify build process. It creates a JSON file with
 * environment variables that get deployed with the site.
 * 
 * Environment variables should be set in Netlify dashboard:
 * - SUPABASE_URL: Your Supabase project URL
 * - SUPABASE_ANON_KEY: Your Supabase Anon Public Key  
 * - ADMIN_PASSWORD: Your admin login password
 */

const fs = require('fs');
const path = require('path');

console.log('🔧 Preparing environment configuration for Netlify...\n');

// Create config object from environment variables
const config = {
  SUPABASE_URL: process.env.SUPABASE_URL || '',
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || '',
  ADMIN_PASSWORD: process.env.ADMIN_PASSWORD || '',
  // Mark that this comes from build-time injection
  SOURCE: 'netlify-build',
  TIMESTAMP: new Date().toISOString()
};

// Create a JavaScript file that sets window.__CONFIG__
const configJS = `
// Auto-generated during Netlify build - DO NOT EDIT
// This file is generated by scripts/inject-env.js

window.__CONFIG__ = ${JSON.stringify(config, null, 2)};
console.log('✓ Environment-injected config loaded (Netlify build)');
`;

// Write to a config file that gets deployed
const configPath = path.join(__dirname, '..', 'js', 'config-env.js');

try {
  fs.mkdirSync(path.dirname(configPath), { recursive: true });
  fs.writeFileSync(configPath, configJS);
  console.log('✓ Created js/config-env.js with injected environment variables');
} catch (error) {
  console.error('✗ Failed to create config file:', error.message);
  process.exit(1);
}

// Validate that required variables are set
const missingVars = [];
if (!process.env.SUPABASE_URL) missingVars.push('SUPABASE_URL');
if (!process.env.SUPABASE_ANON_KEY) missingVars.push('SUPABASE_ANON_KEY');
if (!process.env.ADMIN_PASSWORD) missingVars.push('ADMIN_PASSWORD');

if (missingVars.length > 0) {
  console.warn(`\n⚠️  WARNING: Missing environment variables: ${missingVars.join(', ')}`);
  console.warn('Set these in Netlify dashboard → Site settings → Build & deploy → Environment\n');
} else {
  console.log('✓ All environment variables are set');
}

// Summary
console.log('\n📋 Configuration Summary:');
console.log('   SUPABASE_URL:', config.SUPABASE_URL ? '✓ Set' : '✗ Missing');
console.log('   SUPABASE_ANON_KEY:', config.SUPABASE_ANON_KEY ? '✓ Set' : '✗ Missing');
console.log('   ADMIN_PASSWORD:', config.ADMIN_PASSWORD ? '✓ Set' : '✗ Missing');
console.log('\n✅ Build script completed successfully!\n');
